runtime: nodejs8
instance_class: F2
automatic_scaling:
  max_instances: 10

env_variables:
  REACT_APP_API_KEY: 'af3601e97ca276a3c32d3ccc14937fc8'

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /
    static_dir: build
